name: AntiRGB
version: '1'
main: me.bbb908.antirgb.AntiRGB
api-version: '1.18'
depend: [ProtocolLib]
authors: [bbb908]
description: ProtocolLib anticheat
permissions:
  antirgb.*:
    children:
      - antirgb.viewalerts

  antirgb.viewalerts:
    default: op