name: AnticheatBase
version: '${project.version}'
main: me.bbb908.AnticheatBase.Anticheat
api-version: '1.18'
depend: [ProtocolLib]
authors: [bbb908]
description: ProtocolLib anticheat
permissions:
  antirgb.*:
    children:
      - ac.viewalerts

  antirgb.viewalerts:
    default: op
